---
- name: Use Archiving
  hosts: database_fqdn
  become: true
  tasks:
    - name: ensure /mnt/mysql_backups exists
      file:
        path: /mnt/mysql_backups
        state: directory
        mode: '0755'
    - name: A file /mnt/mysql_backups/database_list.txt 
      lineinfile:
        path: /mnt/mysql_backups/database_list.txt
        line: dev,test,qa,prod
        create: yes
    - name: archive the mysql_backup file
      archive:
        path: /mnt/mysql_backups/database_list.txt
        format: gz
        remove: no
