---
- name: run the geerlingguy.proxy role
  hosts: proxy
  become: true 
  tasks:
    - name: open http on the firewall
      firewalld:
        zone: public
        service: http
        immediate: yes
        permanent: yes
        state: enabled
    - name: restart the firewall
      service:
        name: firewalld
        state: restarted
  roles: 
    - role: geerlingguy.haproxy
      vars:
        haproxy_backend_servers:
          - name: ansible2.example.com
            address: 192.168.11.202:80
          - name: ansible3.example.com
            address: 192.168.11.203:80
        haproxy_backend_balance_method: 'roundrobin'
  
