---
- name: Use Conditionals to Control Play Execution
  hosts: lisenet_fqdn
  become: true
  tasks:
    - name: Change vm.swappiness
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
      when: ansible_memtotal_mb >= 2048
    - name: Display Error Message if Mem less than 2GB
      debug:
        msg: Server Memory Less than 2048MB
      when: ansible_memtotal_mb < 2048

