---
- name: install apache/httpd
  package: 
    name: "{{ web_package }}"
    state: latest

- name: copy the index.html template file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: enable and start the httpd service
  service:
    name: "{{ web_service }}"
    enabled: yes
    state: started

- name: open firewalld for httpd
  firewalld:
    zone: public
    service: "{{ firewall_service }}"
    permanent: yes
    state: enabled

- name: restart the firewalld service
  service:
    name: firewalld
    state: restarted

