---
- name: install exam-3 packages
  hosts: exam 
  tasks: 
    - name: install perl and php on dev, test, and prod
      package:
        name:
          - perl
          - php
        state: latest
      when: "'dev' in group_names or 'prod' in group_names or 'test' in group_names"
    - name: install virtualization host package group on prod
      yum:
        name: "@Virtualization Host"
        state: present
      when: "'prod' in group_names"
    - name: update all packages on production servers
      package:
        name: '*'
        state: latest
      when: "'prod' in group_names"
