---
- name: practice exam c runwebserver.yml
  hosts: prod_fqdn
  tasks:
    - name: install httpd
      package:
        name: httpd
        state: latest
    - name: create /webcontent
      file:
        path: /webcontent
        state: directory
    - name: copy over index.html template
      template:
        src: index.html.j2
        dest: /webcontent/index.html
        mode: '0644' 
    - name: create symlink
      file:
        src: /webcontent/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        state: link
        mode: '0644'
    - name: install firewalld
      package:
        name: firewalld
        state: latest
    - name: start firewalld
      service:
        name: firewalld
        state: started
    - name: open http on firewalld
      firewalld:
        zone: public
        service: http
        state: enabled
        permanent: yes
    - name: restart the firewalld service
      service:
        name: firewalld
        state: restarted
    - name: set selinux to disabled
      selinux:
        state: disabled
    - name: start the httpd service
      service:
        name: httpd
        state: started
