---
- name: install httpd on the webservers
  hosts: exam
  tasks:
    - name: run this block on webservers
      block:
        - name: install httpd and firewalld package
          package:
            name: "{{ item }}"
            state: latest
          loop:
            - "{{ web_package }}"
            - firewalld
        - name: copy the httpd.conf file
          template:
            src: httpd.conf.j2
            dest: "{{ web_config_file }}"
        - name: always trigger restart_httpd 
          command: /bin/true
          notify: restart_httpd
        - name: open firewalld for http
          firewalld:
            zone: public
            service: http
            permanent: yes
            immediate: yes
            state: enabled
      when: "'webservers' in group_names"

  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted
