- name: run the geerlingguy.haproxy role
  become: true
  hosts: proxy
  roles:
  - role: geerlingguy.haproxy
    vars:
      haproxy_backend_servers:
      - name: ansible3
        address: 192.168.11.202:80
      - name: ansible4
        address: 192.168.11.203:80
      haproxy_backend_balance_method: 'roundrobin'
      haproxy_frontend_port: 80
      haproxy_frontend_mode: 'http'


  tasks:
    - name: open port 80
      firewalld:
        service: http
        permanent: true
        immediate: true
        zone: public
        state: enabled
