---
- name: lisenet task 7 scheduled tasks
  hosts: proxy
  become: yes
  tasks: 
    - name: create /var/log/time.log
      file:
        path: /var/log/time.log
        state: touch
        mode: "0644"
    - name: append date to /var/log/time.log every hour
      cron:
        name: date append
        minute: '0'
        user: root
        job: /usr/bin/date >> /var/log/time.log
