---
- name: Create users
  hosts: lisenet
  become: yes
  vars_files:
      - vars/user_list.yml
      - secret.yml
  tasks:
    - name: Ensure group is exist
      group:
        name: wheel
        state: present
    - name: Create users and upload ssh key
      block:
        - name: Create users and upload ssh key
          user:
            name: "{{ item.username }}"
            group: wheel
            password: "{{ user_password | password_hash('sha512') }}"
            shell: /bin/bash
            update_password: on_create
          with_items: "{{ users }}"
        - name: send automation pub key  
          authorized_key:
            user: "{{ item.username }}"
            state: present
            key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
          with_items: "{{ users }}"
      when:
        - ansible_fqdn in groups['webservers_fqdn']
        - "item.uid|string|first == '1'"
    - name: Create users in database
      block:
        - name: Create users and upload ssh key
          user:
            name: "{{ item.username }}"
            group: wheel
            password: "{{ user_password | password_hash('sha512') }}"
            shell: /bin/bash
            update_password: on_create
          with_items: "{{ users }}"
        - name: send automation pub key
          authorized_key:
            user: "{{ item.username }}"
            state: present
            key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
          with_items: "{{ users }}"
      when:
        -  ansible_fqdn in groups['database_fqdn']
        - "item.uid|string|first == '2'"
