---
- name: import http playbook
  hosts: all
  vars:
    - web_dir: /web
    - selinux_type: httpd_sys_content_t
    - web_file: /web/index.html
  tasks:
  - name: run block on webservers
    block:
      - name: setup second disk partition
        parted:
          device: /dev/sdb
          number: 1
          state: present
          part_end: "100%"
          label: gpt
      - name: make /web directory
        file:
          path: "{{ web_dir }}"
          state: directory
          mode: '0755'
      - name: format new drive as xfs
        filesystem:
          fstype: xfs
          dev: /dev/sdb
      - name: mount the new drive to /web
        mount:
          path: "{{ web_dir }}"
          src: /dev/sdb
          fstype: xfs
          state: present
      - name: set selinux type
        sefcontext:
          target: '/web(/.*)?'
          setype: "{{ selinux_type }}"
          state: present
      - name: apply the selinux context
        command: restorecon -irv /web
      - name: copy index.html template to /web
        template:
          src: index.html.j2
          dest: "{{ web_file }}"
    when: "'webservers' in group_names"

  
  - import_role:
        name: http
