---
- name: copy template file
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0444
    force: yes
- name: restart ssh
  service:
    name: sshd
    state: restarted
