---
- name: playbook that configures an LVM volume with the name lvdata in the vgdata volume group
  hosts: all
  tasks:
    - name: check for vgdata
      fail:
        msg: "vgdata does not exist"
      when:
        - ansible_lvm['vgs']['vgdata'] is not defined

    - name: check vgdata size
      fail:
        msg: "insufficient size"
      when:
        - ansible_lvm['vgs']['vgdata']['size_g'] <= "2"
           
    - name: create lvm on vgdata 2GiB+
      lvol:
        vg: vgdata
        lv: lvdata
        size: 2000m
      when: 
        - ansible_lvm['vgs']['vgdata']['size_g'] >= "2"

    - name: set lvdata filesystem
      filesystem:
        dev: /dev/vgdata/lvdata
        fstype: xfs

    - name: create /lvdata directory
      file:
        path: /lvdata
        state: directory
    
    - name: mount lvdata to /lvdata
      mount:
        path: /lvdata
        src: /dev/vgdata/lvdata
        fstype: xfs
        state: present
...
