---
- name: create user david with aes256 encoded password from ansible vault
  hosts: control.example.com
  tasks:
    - name: create user david
      user:
        name: david
        group: wheel
        password: "{{ user_pass | password_hash('sha512', 'supersalty') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        shell: /bin/bash
        update_password: always        

    - name: debug variable output
      debug:
        msg: "{{ user_pass }}"
