---
- name: managing storage exam preparation
  hosts: ansible1.example.com
  tasks:
  - name: create partition on ansible1
    parted: 
      device: /dev/sdb
      number: 1
      state: present
      part_end: 1GiB

- name: create 3GiB partition on /dev/sdb1 on ansible3
  hosts: ansible3.example.com
  tasks:
  - name: create partition on ansibel3
    parted:
      device: /dev/sdb
      number: 1
      state: present
      part_end: 3GiB
    
- name: setup a volume group on all hosts on which the disk /dev/sdb is defined
  hosts: all
  tasks:
  - name: create lvm
    lvg:
      vg: vgdata
      pvs: /dev/sdb1
      pesize: "32"
    when: ansible_devices.sdb is defined
