---
- name: gather facts about packages
  hosts: control
  tasks:
    - name: gather package information as facts
      package_facts:
        manager: auto
    - name: copy version info to file
      lineinfile:
        line: "{{ item }}={{ ansible_facts.packages[item][0].version }}"
        path: /home/ansible/packages.txt
        create: yes
      loop:
        - kernel
        - bash
        - glibc
