---
- name: setup exam-b ftp reposerver from iso
  hosts: control
  tasks:
    - name: create /var/ftp/repo directory
      file:
        path: /var/ftp/repo
        state: directory
    - name: mount the iso to /var/ftp/repo
      mount:
        src: /dev/sr0
        path: /var/ftp/repo
        fstype: iso9660
        opts: ro
        state: mounted
    - name: disable the firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: enable anonymous vsftpd access
      template:
        src: vsftpd.conf.j2
        dest: /etc/vsftpd/vsftpd.conf
    - name: start vsftpd 
      service:
        name: vsftpd
        state: started
        enabled: yes
