---
- name: setup storage on second device
  hosts: exam_fqdn
  tasks: 
  - name: run block if sdb is present
    block:
      - name: create a 5GiB partition
        parted:
          device: /dev/sdb
          number: 1
          state: present
          part_end: "100%"
      - name: create the vgdata volume group
        lvg:
          vg: vgdata
          pvs: /dev/sdb1
          pesize: '8'
      - name: create the lvdata logical volume
        lvol: 
          vg: vgdata
          lv: lvdata
          size: 1g
      - name: format lvdata to ext3
        filesystem:
          fstype: ext3
          dev: /dev/mapper/vgdata-lvdata
      - name: create /data directory
        file:
          path: /data
          state: directory
      - name: create fstab /dev/sdb1 to /data persistently
        mount:
          src: /dev/mapper/vgdata-lvdata
          path: /data
          fstype: ext3
          state: present
      - name: mount /data
        mount:
          src: /dev/mapper/vgdata-lvdata
          path: /data
          fstype: ext3
          state: mounted

    when: "'sdb' in  ansible_devices"


...
