---
- name: use ansible vault variables
  hosts: control
  vars_files:
    cloudpass.yml
  tasks:
    - name: echo cloudid to file
      lineinfile:
        path: /home/ansible/cloudcreds.txt
        line: 'CLOUDID={{ CLOUDID }}'
        create: yes
    - name: echo cloudpass to file
      lineinfile:
        path: /home/ansible/cloudcreds.txt
        line: 'CLOUDPASS={{ CLOUDPASS }}'
