---
- name: A primary partition number 1 of size 800MB on device /dev/sdb is created.
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_end: 800MiB
- name: An LVM volume group called vg_database is created that uses the primary partition created above.
  lvg:
    vg: vg_database
    pvs: /dev/sdb1
    pesize: '32'
- name: An LVM logical volume called lv_mysql is created of size 512MB in the volume group vg_database
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: '512'
- name: An XFS filesystem on the logical volume lv_mysql is created.
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_database-lv_mysql
- name: create /mnt/mysql_backups
  file:
    path: /mnt/mysql_backups
    state: directory
    mode: '0644'
- name: Logical volume lv_mysql is permanently mounted on /mnt/mysql_backups.
  mount:
    path: /mnt/mysql_backups
    src: /dev/mapper/vg_database-lv_mysql
    fstype: xfs
    state: mounted
- name: disable os native mysql package
  shell: yum module disable mysql -y
  warn: false
- name: mysql-community-server package is installed.
  package:
    name: 
      - mysql-community-server
      - perl
    state: latest
- name: Firewall is configured to allow all incoming traffic on MySQL port TCP 3306.
  firewalld:
    zone: public
    port: 3306/tcp 
    immediate: yes
    permanent: yes
    state: enabled
#- name: MySQL root user password should be set from the variable database_password
#  community.mysql.mysql_user:
#    name: root
#    password: "{{ database_password | password_hash('sha512') }}" 

- name: MySQL server should be started and enabled on boot.
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - mysqld
    - firewalld
- name: MySQL server configuration file is generated from the my.cnf.j2 Jinja2 template
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: '0644'




