---
- hosts: exam
  vars:
    timesync_ntp_servers:
      - hostname: 192.168.11.200
        iburst: yes
    timesync_step_threshold: 0

  roles:
    - rhel-system-roles.timesync

  tasks:
    - name: install ntpstat
      package:
        name: ntpstat
        state: latest

    - name: report ntp sync
      shell: ntpstat
      register: ntp_status
      failed_when: "'SUCCESS' in ntp_status"

    - debug:
        msg: "Unfortunately time could not be synchronized"
      when: "'unsynchronised' in ntp_status.stdout_lines"
